language: node_js
node_js: 
  - lts/*
services:
  - docker
install:
  - echo TRAVIS_COMMIT
  - ls
  - npm build
  - docker build -t gwdowner/webservice:latest .
  - docker images
  - npm install
script:
  - npm run coveralls
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

